### ISSUE TITLE
Script Crashes

### ISSUE THREAD

**Issue by kfoxton** [tenekev/immich-auto-stack#11]
Hi,

I recently imported my external library of photos, which I have both JPG and RAW, of each image, and was hoping to use your script to stack them together, but it seems like it is failing in counting?  This happens after a few minutes of no output in the console:  The below is the output:

/script # ./immich_auto_stack.py 
2024-09-05 17:58:56,229 - INFO - ============== INITIALIZING ==============
2024-09-05 17:58:56,229 - INFO - ⬇️  Fetching assets: 
2024-09-05 17:58:56,230 - INFO -    Page size: 1000
2024-09-05 18:03:03,806 - INFO -    Pages: None
2024-09-05 18:03:03,806 - INFO -    Assets: 157831
Traceback (most recent call last):
  File "/script/./immich_auto_stack.py", line 226, in <module>
    main()
  File "/script/./immich_auto_stack.py", line 200, in main
    children_id = [x['id'] for x in stack[1:] if x['stackCount'] == None ]
                                                 ~^^^^^^^^^^^^^^
KeyError: 'stackCount'

Running as a Docker image, on UnRaid. Immich server version 1.113.0

**Comment by kfoxton** [comment]
Just want to add, prior to adding my external library, and only having 20K pictures in Immich, the script was able to run without issue.

**Comment by tenekev** [comment]
We know of the issue. It was introduced in the latest update because they refactored the whole stack functionality. The discussion is over in issue #10 so I'm going to close this. Basically, I'll update the script as soon as I can.
